export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUCT_DETAIL_REQUEST = "PRODUCT_DETAIL_REQUEST";
export const PRODUCT_DETAIL_SUCCESS = "PRODUCT_DETAIL_SUCCESS";
export const PRODUCT_DETAIL_FAIL = "PRODUCT_DETAIL_FAIL";

export const PRODUCT_SERVICEABILITY_REQUEST = "PRODUCT_SERVICEABILITY_REQUEST";
export const PRODUCT_SERVICEABILITY_SUCCESS = "PRODUCT_SERVICEABILITY_SUCCESS";
export const PRODUCT_SERVICEABILITY_FAIL = "PRODUCT_SERVICEABILITY_FAIL";

export const PRODUCT_LATEST_LIST_REQUEST = "PRODUCT_LATEST_LIST_REQUEST";
export const PRODUCT_LATEST_LIST_SUCCESS = "PRODUCT_LATEST_LIST_SUCCESS";
export const PRODUCT_LATEST_LIST_FAIL = "PRODUCT_LATEST_LIST_FAIL";
