const products = [
  {
    _id: "001",
    name: "Screwdriver Set",
    image: "/products/001/cover.jpg",
    description: "Jackly Screwdriver Set",
    brand: "Jackly",
    category: "Tools",
    price: 450,
    countInStock: 20,
    rating: 4.1,
    numReviews: 4,
  },
  {
    _id: "002",
    name: "Philips Trimmer",
    image: "/products/002/cover.jpg",
    description: "Philips Trimmer !",
    brand: "Philips",
    category: "Tools",
    price: 799,
    countInStock: 20,
    rating: 4.4,
    numReviews: 4,
  },
  {
    _id: "003",
    name: "Logitech Keyboard",
    image: "/products/003/cover.jpg",
    description: "Logitech Keyboard : minimal simple keyboard",
    brand: "Logitech",
    category: "Tools",
    price: 299,
    countInStock: 20,
    rating: 4,
    numReviews: 4,
  },
  {
    _id: "004",
    name: "Logitech g502 Mouse",
    image: "/products/004/cover.jpg",
    description: "Logitech g502 Mouse ",
    brand: "Vithamas",
    category: "Smart Bulb",
    price: 32999,
    countInStock: 20,
    rating: 3,
    numReviews: 4,
  },
  {
    _id: "005",
    name: "Vithamas Led Light Stip",
    image: "/products/005/cover.jpg",
    description: "Vithamas Led Light Stip ",
    brand: "Vithamas",
    category: "Smart Bulb",
    price: 1999,
    countInStock: 20,
    rating: 4,
    numReviews: 4,
  },
  {
    _id: "006",
    name: "HyperX Mechanical Keyboard",
    image: "/products/006/cover.jpg",
    description: "Geforce 2060 super 8gb ",
    brand: "Vithamas",
    category: "Smart Bulb",
    price: 32999,
    countInStock: 20,
    rating: 4,
    numReviews: 4,
  },
  {
    _id: "007",
    name: "GTX 2060 Super",
    image: "/products/007/cover.jpg",
    description: "Geforce 2060 super 8gb ",
    brand: "Vithamas",
    category: "Smart Bulb",
    price: 32999,
    countInStock: 20,
    rating: 4,
    numReviews: 4,
  },
  {
    _id: "008",
    name: "Wipro Wi-Fi Enabled Smart LED",
    image: "/products/008/cover.jpg",
    description:
      "Wipro Wi-Fi Enabled Smart LED Bulb B22 9-Watt (Pack of 1, Shades of White and Yellow) Compatible with Amazon Alexa and Google Assistant",
    brand: "Wipro",
    category: "Smart Bulb",
    price: 469,
    countInStock: 20,
    rating: 4,
    numReviews: 4,
  },
  {
    _id: "009",
    name: "White 25W LED Strip",
    image: "/products/009/cover.jpg",
    description:
      "White 25W LED Strip 2835 Cove Light 5 Metre (Cool White, Pack of 1) with Driver",
    brand: "White",
    category: "Smart Bulb",
    price: 576,
    countInStock: 20,
    rating: 1,
    numReviews: 4,
  },
  {
    _id: "010",
    name: "Murphy 25W LED Strip",
    image: "/products/010/cover.jpg",
    description:
      "Murphy 25W LED Strip 2835 Cove Light 5 Metre (Cool White, Pack of 1) with Driver",
    brand: "Murphy",
    category: "Smart Bulb",
    price: 576,
    countInStock: 20,
    rating: 2,
    numReviews: 4,
  },
  {
    _id: "011",
    name: "Radiato ES Led Strip(Rope)",
    image: "/products/011/cover.jpg",
    description:
      "Radiato ES Led Strip(Rope) SMD Roll Super Thin 3014 Waterproof with Adapter. (Warm White, 5 Meter)",
    brand: "Radiato",
    category: "Smart Bulb",
    price: 368,
    countInStock: 20,
    rating: 1,
    numReviews: 4,
  },
  {
    _id: "012",
    name: "GloSmart LED Bulb",
    image: "/products/012/cover.jpg",
    description:
      "GloSmart LED BULB !! GloSmart LED BULB !! GloSmart LED BULB !! ",
    brand: "Vithamas",
    category: "Smart Bulb",
    price: 999,
    countInStock: 20,
    rating: 3,
    numReviews: 4,
  },
];
export default products;

// Colors Smart WiFi Strip
