// sales info fetch information
export const SALES_INFO_REQUEST = "SALES_INFO_REQUEST";
export const SALES_INFO_SUCCESS = "SALES_INFO_SUCCESS";
export const SALES_INFO_FAIL = "SALES_INFO_FAIL";
// sales analytics
export const SALES_ANALYTICS_REQUEST = "SALES_ANALYTICS_REQUEST";
export const SALES_ANALYTICS_SUCCESS = "SALES_ANALYTICS_SUCCESS";
export const SALES_ANALYTICS_FAIL = "SALES_ANALYTICS_FAIL";
// revenue analytics
export const REVENUE_ANALYTICS_REQUEST = "REVENUE_ANALYTICS_REQUEST";
export const REVENUE_ANALYTICS_SUCCESS = "REVENUE_ANALYTICS_SUCCESS";
export const REVENUE_ANALYTICS_FAIL = "REVENUE_ANALYTICS_FAIL";
// earning reports
export const EARNING_REPORTS_REQUEST = "EARNING_REPORTS_REQUEST";
export const EARNING_REPORTS_SUCCESS = "EARNING_REPORTS_SUCCESS";
export const EARNING_REPORTS_FAIL = "EARNING_REPORTS_FAIL";
// SOURCES
export const SOURCES_INFO_REQUEST = "SOURCES_INFO_REQUEST";
export const SOURCES_INFO_SUCCESS = "SOURCES_INFO_SUCCESS";
export const SOURCES_INFO_FAIL = "SOURCES_INFO_FAIL";
// TRANSACTIONS
export const TRANSACTIONS_INFO_REQUEST = "TRANSACTIONS_INFO_REQUEST";
export const TRANSACTIONS_INFO_SUCCESS = "TRANSACTIONS_INFO_SUCCESS";
export const TRANSACTIONS_INFO_FAIL = "TRANSACTIONS_INFO_FAIL";
