// Admin login and logout related
export const ADMIN_LOGIN_REQUEST = "ADMIN_LOGIN_REQUEST";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAIL = "ADMIN_LOGIN_FAIL";
export const ADMIN_LOGOUT = "ADMIN_LOGOUT";
export const ADMIN_TOKEN_UPDATED = "ADMIN_TOKEN_UPDATED";

export const ADMIN_LOGIN_STATUS_REQUEST = "ADMIN_LOGIN_STATUS_REQUEST";
export const ADMIN_LOGIN_STATUS_SUCCESS = "ADMIN_LOGIN_STATUS_SUCCESS";
export const ADMIN_LOGIN_STATUS_FAIL = "ADMIN_LOGIN_STATUS_FAIL";
