// customer login and logout related
export const CUSTOMER_LOGIN_REQUEST = "CUSTOMER_LOGIN_REQUEST";
export const CUSTOMER_LOGIN_SUCCESS = "CUSTOMER_LOGIN_SUCCESS";
export const CUSTOMER_LOGIN_FAIL = "CUSTOMER_LOGIN_FAIL";
export const CUSTOMER_LOGOUT = "CUSTOMER_LOGOUT";
export const CUSTOMER_TOKEN_UPDATED = "CUSTOMER_TOKEN_UPDATED";
// customer registration related
export const CUSTOMER_REGISTER_REQUEST = "CUSTOMER_REGISTER_REQUEST";
export const CUSTOMER_REGISTER_SUCCESS = "CUSTOMER_REGISTER_SUCCESS";
export const CUSTOMER_REGISTER_FAIL = "CUSTOMER_REGISTER_FAIL";
// Fetching customer profile details
export const CUSTOMER_PROFILE_DETAILS_FETCH_REQUEST =
  "CUSTOMER_PROFILE_DETAILS_FETCH_REQUEST";
export const CUSTOMER_PROFILE_DETAILS_FETCH_SUCCESS =
  "CUSTOMER_PROFILE_DETAILS_FETCH_SUCCESS";
export const CUSTOMER_PROFILE_DETAILS_FETCH_FAIL = "USER_DETAILS_FETCH_FAIL";
// updating the customer profile details
export const CUSTOMER_PROFILE_DETAILS_UPDATE_REQUEST =
  "CUSTOMER_PROFILE_DETAILS_UPDATE_REQUEST";
export const CUSTOMER_PROFILE_DETAILS_UPDATE_SUCCESS =
  "CUSTOMER_PROFILE_DETAILS_UPDATE_SUCCESS";
export const CUSTOMER_PROFILE_DETAILS_UPDATE_FAIL =
  "CUSTOMER_PROFILE_DETAILS_UPDATE_FAIL";
export const CUSTOMER_PROFILE_DETAILS_UPDATE_RESET =
  "CUSTOMER_PROFILE_DETAILS_UPDATE_RESET";
export const CUSTOMER_ADDRESS_FETCH_REQUEST = "CUSTOMER_ADDRESS_FETCH_REQUEST";
export const CUSTOMER_ADDRESS_FETCH_SUCCESS = "CUSTOMER_ADDRESS_FETCH_SUCCESS";
export const CUSTOMER_ADDRESS_FETCH_FAIL = "CUSTOMER_ADDRESS_FETCH_FAIL";

export const CUSTOMER_ADDRESS_CREATE_REQUEST =
  "CUSTOMER_ADDRESS_CREATE_REQUEST";
export const CUSTOMER_ADDRESS_CREATE_SUCCESS =
  "CUSTOMER_ADDRESS_CREATE_SUCCESS";
export const CUSTOMER_ADDRESS_CREATE_FAIL = "CUSTOMER_ADDRESS_CREATE_FAIL";
