export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_TOKEN_UPDATED = "USER_TOKEN_UPDATED";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
// Fetching user details
export const USER_DETAILS_FETCH_REQUEST = "USER_DETAILS_FETCH_REQUEST";
export const USER_DETAILS_FETCH_SUCCESS = "USER_DETAILS_FETCH_SUCCESS";
export const USER_DETAILS_FETCH_FAIL = "USER_DETAILS_FETCH_FAIL";
// updating the user details
export const USER_DETAILS_UPDATE_REQUEST = "USER_DETAILS_UPDATE_REQUEST";
export const USER_DETAILS_UPDATE_SUCCESS = "USER_DETAILS_UPDATE_SUCCESS";
export const USER_DETAILS_UPDATE_FAIL = "USER_DETAILS_UPDATE_FAIL";
export const USER_DETAILS_UPDATE_RESET = "USER_DETAILS_UPDATE_RESET";
