import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faStar,
  faStarHalfAlt,
  faStarHalf,
  faShoppingCart,
  faUser,
  faUserAlt,
  faTrash,
  faTruck,
  faUserPlus,
  faSignInAlt,
  faSignOutAlt,
  faCartPlus,
  faTrashAlt,
  faListAlt,
  faSearch,
  faAngleLeft,
  faAngleRight,
  faPaperPlane,
  faMapMarker,
  faMapMarkerAlt,
} from "@fortawesome/free-solid-svg-icons";

import {
  faFacebook,
  faPinterest,
  faTwitter,
  faInstagram,
  faCcMastercard,
  faCcPaypal,
  faCcVisa,
  faYoutube,
  faAmazon,
  faFacebookF,
} from "@fortawesome/free-brands-svg-icons";

library.add(
  faStar,
  faStarHalfAlt,
  faStarHalf,
  faShoppingCart,
  faUser,
  faUserAlt,
  faTrash,
  faTruck,
  faUserPlus,
  faSignInAlt,
  faSignOutAlt,
  faCartPlus,
  faTrashAlt,
  faListAlt,
  faSearch,
  faAngleLeft,
  faAngleRight,
  faFacebook,
  faPinterest,
  faInstagram,
  faCcMastercard,
  faCcPaypal,
  faCcVisa,
  faPaperPlane,
  faTwitter,
  faYoutube,
  faInstagram,
  faMapMarker,
  faMapMarkerAlt,
  faAmazon,
  faFacebookF
);
