import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faStar,
  faStarHalfAlt,
  faStarHalf,
  faShoppingCart,
  faUser,
  faUserAlt,
  faTrash,
  faTruck,
  faUserPlus,
  faSignInAlt,
  faSignOutAlt,
  faCartPlus,
  faTrashAlt,
  faListAlt,
  faSearch,
  faAngleLeft,
  faAngleRight,
  faPaperPlane,
} from "@fortawesome/free-solid-svg-icons";

import {
  faFacebook,
  faPinterest,
  faInstagram,
  faLinkedin,
  faCcMastercard,
  faPaypal,
  faCcVisa,
} from "@fortawesome/free-brands-svg-icons";

library.add(
  faStar,
  faStarHalfAlt,
  faStarHalf,
  faShoppingCart,
  faUser,
  faUserAlt,
  faTrash,
  faTruck,
  faUserPlus,
  faSignInAlt,
  faSignOutAlt,
  faCartPlus,
  faTrashAlt,
  faListAlt,
  faSearch,
  faAngleLeft,
  faAngleRight,
  faFacebook,
  faPinterest,
  faInstagram,
  faLinkedin,
  faCcMastercard,
  faPaypal,
  faCcVisa
);
