ORDER_PLACED_STATUS = "ORDER_PLACED"
ORDER_SHIPPED_STATUS = "ORDER_SHIPPED_STATUS"
ORDER_PAYMENT_FAILED_STATUS = "ORDER_PAYMENT_SUCCESS_STATUS"
ORDER_DELIVERED_STATUS = "ORDER_DELIVERED_STATUS"


TIMESTAMP_FORMAT = "%Y-%m-%d %H:%M:%S"